resource "fortios_system_vdomlink" "v-001-002-" {
  name = "v-001-002-"
}

resource "fortios_system_interface" "v-001-002-0" {
  vrf = 1
  ip            = "10.254.102.1 255.255.255.252"
  #interface = fortios_system_vdomlink.v-001-002-.name
  name          = "v-001-002-0"
  vdom          = "root"
  description   = "Created by Terraform Provider for FortiOS"
  autogenerated = "auto"
}

resource "fortios_system_interface" "v-001-002-1" {
  vrf = 2
  ip            = "10.254.102.2 255.255.255.252"
  #interface = fortios_system_vdomlink.v-001-002-.name
  name          = "v-001-002-1"
  vdom          = "root"
  description   = "Created by Terraform Provider for FortiOS"
  autogenerated = "auto"
}


resource "fortios_router_prefixlist" "ia-prefix-list-leak-default" {
  name = "ia-prefix-list-leak-default"
  rule {
    action = "permit"
    prefix = "0.0.0.0 0.0.0.0"
  }
}

resource "fortios_router_prefixlist" "ia-prefix-list-leak-non-rfc1918" {
  name = "ia-prefix-list-leak-non-rfc1918"
  rule {
    action = "deny"
    prefix = "10.0.0.0 255.0.0.0"
    le = 32
  }
  rule {
    action = "deny"
    prefix = "172.16.0.0 255.240.0.0"
    le = 32
  }
  rule {
    action = "deny"
    prefix = "192.168.0.0 255.255.0.0"
    le = 32
  }
  rule {
    action = "permit"
    prefix = "0.0.0.0 0.0.0.0"
    le = 32
  }
}

resource "fortios_router_routemap" "route-map-leak-001-to-002" {
  name = "route-map-leak-001-to-002"

  rule {
    match_ip_address = fortios_router_prefixlist.ia-prefix-list-leak-default.name
  }
}

resource "fortios_router_routemap" "route-map-leak-002-to-001" {
  name = "route-map-leak-002-to-001"

  rule {
    match_ip_address = fortios_router_prefixlist.ia-prefix-list-leak-non-rfc1918.name
  }
}